#+TITLE: Parinfer Mode
#+AUTHOR: DogLooksGood

* Table of contents
- [[#what-is-parinfer][What Is Parinfer]]
- [[#installation][Installation]]
- [[#indent-and-paren-modes][Indent And Paren Modes]]
- [[#credits][Credits]]
- [[#license][License]]

* What Is Parinfer
*Parinfer* is a proof-of-concept editor mode for Lisp programming languages. 
It will infer some changes to keep Parens and Indentation inline with one another.
Parinfer consists of two modes:

- Indent Mode :: Indent Mode gives you full control of indentation, while Parinfer corrects or inserts close-parens
where appropriate.
- Paren Mode :: Paren Mode gives you full control of parens, while Parinfer corrects indentation.

To learn more about Parinfer, please take a look at its [[https://shaunlebron.github.io/parinfer/][home page]].

And the *parinfer-mode* is the implementation on Emacs with [[https://github.com/oakmac/parinfer-elisp][parinfer-elisp]].

* Installation
Parinfer is available on MELPA(and MELPA Stable) now, I recommend to install with [[https://github.com/jwiegley/use-package][use-package]].

Add following code to your ~.emacs~ or ~init.el~.

#+BEGIN_SRC elisp
  (use-package parinfer
    :ensure t
    :bind
    (("C-," . parinfer-toggle-mode))
    :init
    (progn
      (add-hook 'clojure-mode-hook #'parinfer-mode)
      (add-hook 'emacs-lisp-mode-hook #'parinfer-mode)))
#+END_SRC

* Indent And Paren Modes.
Toggle *Indent Mode* and *Paren Mode* with command ~parinfer-toggle-mode~.

Whenever you switch to *Indent Mode*, parinfer-mode will correct all parens of current buffer.

When the first time, you switch to *Indnet Mode*, if the buffer will be modified, you will see a confirm message.
Press ~y~ to  switch to *Indent Mode* and let parinfer-mode modify the buffer.
Press ~n~ to stay in *Paren Mode*.

After opening a file, the parinfer-mode enable *Indent Mode* if it won't make any changes. 
Otherwise, *Paren Mode* will be enabled.

You can use ~parinfer-diff~ command to see how will *Indent Mode* modify the buffer with ~Ediff~.

And there are some keybindings in Ediff:
| Key  | Description                                               |
|------+-----------------------------------------------------------|
| ~q~  | Quit diff.                                                |
| ~b~  | B->A in Ediff, this can apply change to your origin code. |
| ~ra~ | Restore A in Ediff, this can revert change.               |
| ~n~  | Move to next difference.                                  |
| ~p~  | Move to previous difference.                              |

Alternatively, there's a command ~parinfer-auto-fix~ to fix wrong indentation for whole buffer. (Only works with balanced parens)


* Credits
- [[https://github.com/shaunlebron][shaunlebron]] :: Create [[https://shaunlebron.github.io/parinfer/][Parinfer]].
- [[https://github.com/oakmac][oakmac]] :: Bring Parinfer to Emacs with [[https://github.com/oakmac/parinfer-elisp][parinfer-elisp]].
- [[https://github.com/tumashu][tumashu]] :: Help me a lot in writing this plugin.
- [[https://github.com/purcell][purcell]] & [[https://github.com/syohex][syohex]] :: Advice and Tips for writing emacs plugin

* License
parinferlib.el from [[https://github.com/oakmac/parinfer-elisp][parinfer-elisp]], is licensed under [[https://github.com/oakmac/parinfer-elisp/blob/master/LICENSE.md][ISC]].
Licensed under the GPLv3.
